### PR TITLE
RDF* support

### PR DESCRIPTION
**Pull request by pragya16067**
Support added for parsing RDF* graphs. 
Additional code in parser for Turtle, i.e. notation3.py to change any embedded triples to reification statements. 
Tested for graphs with multiple embedded statements and examples to test for RDF* embedded triples as subject, object, both subject and object and recursively embedded triples.

### CODE REVIEW

**Comment by JervenBolleman** [comment]
@pragya16067 very nice work. I am not sure if we need configure the turtle parser to by "normal"turtle and "turtlestar". Something for the maintainers to look into.

**Comment by JervenBolleman** [comment]
Actually @pragya16067 I think you should open a PR request against the main rdflib repository. So that the maintainers can review the issue.

**Comment by pragya16067** [comment]
Hi @JervenBolleman, I added this PR here as the issue (https://github.com/RDFLib/rdflib/issues/955) was to add support for SPARQL* as well as RDF*, hence it made sense to be included here with the SPARQL* work.

**Comment by pragya16067** [comment]
Nevertheless, I will add a PR on the main rdflib repository. Thanks!

**Pull request closed without merging**
